# Setup
title: Amin Laanaya
url: https://bobcycle.github.io/Blog-1
paginate: 1
paginate_path: "/Blog-1/page:num/"
baseurl: "/Blog-1"
permalink: pretty

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
sass:
  sass_dir: _sass
  style: ':compressed'
author:
  name: Amin Laanaya
  url: 'https://laanaya.org'
  email: amin@laanaya.org
version: 3.0.0
nav:
  - title: Blog
    url: /Blog-1/archive
  - title: About
    url: /Blog-1/about
