# Setup
title: Amin Laanaya
url: https://bobcycle.github.io/Blog
paginate: 1
paginate_path: "/Blog/page:num/"
baseurl: "/Blog"
permalink: pretty

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
sass:
  sass_dir: _sass
  style: ':compressed'
author:
  name: Amin Laanaya
  url: 'https://laanaya.org'
  email: amin@laanaya.org
version: 3.0.0
nav:
  - title: Archive
    url: /Blog/archive
#  - title: Home
#    url: https://laanaya.org/
